{"name": "test_logging_in_with_Invalid_credentials", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('setup_and_teardown', <FixtureRequest for <Function test_logging_in_with_Invalid_credentials>>)", "trace": "file C:\\Users\\shambhu nath giri\\PycharmProjects\\FirstPythonProject\\python\\selenium\\dr\\test_pytestfixtures.py, line 11\n  def test_logging_in_with_Invalid_credentials(setup_and_teardown):\nE       fixture 'setup_and_teardown' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\shambhu nath giri\\PycharmProjects\\FirstPythonProject\\python\\selenium\\dr\\test_pytestfixtures.py:11"}, "start": 1720110603003, "stop": 1720110603003, "uuid": "00481750-3da1-4ac5-857f-dc16ddbb2fbf", "historyId": "691353a5f82a891514332b3d550a8175", "testCaseId": "691353a5f82a891514332b3d550a8175", "fullName": "python.selenium.dr.test_pytestfixtures#test_logging_in_with_Invalid_credentials", "labels": [{"name": "parentSuite", "value": "python.selenium.dr"}, {"name": "suite", "value": "test_pytestfixtures"}, {"name": "host", "value": "DESKTOP-UI2KGFP"}, {"name": "thread", "value": "13356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "python.selenium.dr.test_pytestfixtures"}]}